/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { layer_a$_T } from './layer_a$_b.js'
import type { top_layer$_T } from './top_layer$_b.js'
import type { top_layer_zIndex$_T } from './top_layer_zIndex$_b.js'
export interface layer_ctx_I {
	layer_a$?:layer_a$_T
	top_layer$?:top_layer$_T
	top_layer_zIndex$?:top_layer_zIndex$_T
}